In [423]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

%matplotlib qt

In [424]:
cap = cv.VideoCapture('video/traffic.mp4')

In [425]:
x, y, w, h = 395, 0, 40, 40
track_window = (x, y, w, h)
ret, frame = cap.read()
frame_rgb = cv.cvtColor(frame, cv.COLOR_BGR2RGB)
roi = frame[y:y+h, x:x+w]

In [426]:
hsv_roi = cv.cvtColor(roi, cv.COLOR_BGR2HSV)
plt.imshow(hsv_roi)

In [427]:
mask = cv.inRange(roi, np.array((113., 17., 250.)), np.array((255., 255., 255.)))
roi_hist = cv.calcHist([hsv_roi], [0], mask, [180], [0, 180])
cv.normalize(roi_hist, roi_hist, 0, 255, cv.NORM_MINMAX)
term_crit = (cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1)

In [428]:
cv.namedWindow('traffic', cv.WINDOW_NORMAL)
while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv], [0], roi_hist, [0, 180], 1)
        ret, track_window = cv.CamShift(dst, track_window, term_crit)
        pts = cv.boxPoints(ret)
        pts = np.int0(pts)
        print(pts)
        final_image = cv.polylines(frame, [pts], True, (0, 255, 0), 2)
        #x, y, w, h = track_window
        #final_image = cv.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv.imshow('traffic', final_image)
    else:
        cap.set(cv.CAP_PROP_POS_FRAMES, 0)
        x, y, w, h = 395, 0, 40, 40
        track_window = (x, y, w, h)
        continue

    if cv.waitKey(10) & 0xFF == ord('q'):
        break

[[400  20]
 [409   0]
 [419   3]
 [410  24]]
[[407   3]
 [417  16]
 [410  21]
 [400   8]]
[[405   9]
 [417  14]
 [414  20]
 [402  15]]
[[416   4]
 [420  20]
 [408  23]
 [404   7]]
[[408   6]
 [422  18]
 [415  25]
 [401  13]]
[[417   7]
 [419  23]
 [406  25]
 [404   9]]
[[408   7]
 [424  17]
 [418  26]
 [402  16]]
[[411   5]
 [423  21]
 [413  28]
 [401  12]]
[[412   6]
 [424  23]
 [414  30]
 [402  13]]
[[411   9]
 [422  20]
 [415  28]
 [404  17]]
[[411  10]
 [422  23]
 [414  30]
 [403  17]]
[[413   8]
 [424  26]
 [415  32]
 [404  14]]
[[411  10]
 [423  25]
 [414  32]
 [402  17]]
[[411   9]
 [426  25]
 [416  34]
 [401  18]]
[[413  10]
 [425  27]
 [416  34]
 [404  17]]
[[415  10]
 [426  28]
 [415  35]
 [404  17]]
[[415  12]
 [427  30]
 [417  37]
 [405  19]]
[[412  17]
 [427  26]
 [421  36]
 [406  27]]
[[411  19]
 [428  27]
 [423  36]
 [406  28]]
[[412  21]
 [427  28]
 [422  37]
 [407  30]]
[[414  15]
 [428  31]
 [417  40]
 [403  24]]
[[415  15]
 [430  32]
 [419  42]
 [404  25]]
[[416  17]

In [429]:
cap.release()
cv.destroyAllWindows()