#### SVD

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1, 2, 0],
                   [0, 0, 5],
                   [3, -4, 2],
                   [1, 6, 5],
                   [0, 1, 0]])

In [7]:
U, S, VT = np.linalg.svd(matrix, full_matrices=False)

In [8]:
print("Матрица U:")
print(U)
print("\nСингулярные значения S:")
print(np.diag(S))
print("\nТранспонированная матрица VT:")
print(VT)

Матрица U:
[[ 0.17056501  0.15680918 -0.53077508]
 [ 0.39287016 -0.52933945  0.6134793 ]
 [-0.14366152 -0.82449256 -0.52379105]
 [ 0.88843702  0.06074346 -0.24655277]
 [ 0.08125046  0.10831843 -0.08231425]]

Сингулярные значения S:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]]

Транспонированная матрица VT:
[[ 0.07116451  0.71702467  0.69340553]
 [-0.36737824  0.66514082 -0.65009301]
 [-0.92734505 -0.20847855  0.31075368]]


In [9]:
reconstructed_matrix = U @ np.diag(S) @ VT
print("\nВосстановленная матрица:")
print(reconstructed_matrix)


Восстановленная матрица:
[[ 1.00000000e+00  2.00000000e+00  5.65636386e-16]
 [-4.73124203e-16 -1.74120585e-15  5.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  6.00000000e+00  5.00000000e+00]
 [ 5.80854123e-17  1.00000000e+00 -7.94730681e-17]]


In [11]:
Sigma = np.diag(S)

reconstructed_matrix = np.dot(U, np.dot(Sigma, VT))
print("\nВосстановленная матрица:")
print(reconstructed_matrix)


Восстановленная матрица:
[[ 1.00000000e+00  2.00000000e+00  5.36411240e-16]
 [-5.44008204e-16 -1.60096537e-15  5.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  6.00000000e+00  5.00000000e+00]
 [ 4.68416322e-17  1.00000000e+00 -9.41139080e-17]]


#### Euclidean norm

In [15]:
euclidean_norm = np.linalg.norm(matrix, ord=2)
euclidean_norm

8.824868854820444

In [16]:
S[0]

8.824868854820442

#### Frobenius norm

In [18]:
frobenius_norm = np.linalg.norm(matrix, 'fro')
frobenius_norm

11.045361017187261