In [79]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

plt.style.use('dark_background')

In [80]:
iris = load_iris()
X = iris.data
y = iris.target

In [81]:
def standard_scale(x):
    return (x - x.mean(axis=0)) / x.std(axis=0)

In [82]:
X = standard_scale(X)
X[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=111)
log_model1 = LogisticRegression()
log_model1.fit(X_train, y_train)
y_pred1 = log_model1.predict(X_test)

print(f'Weight of model:\n{log_model1.coef_}\n')
print(f'Intercept: {log_model1.intercept_}\n')
print(f'True values:\n{y_test}\n')
print(f'Predict values:\n{y_pred1}\n')

Weight of model:
[[-1.06544633  0.98533688 -1.80102613 -1.69556947]
 [ 0.64321104 -0.49815865 -0.37938192 -0.76932409]
 [ 0.42223528 -0.48717824  2.18040806  2.46489356]]

Intercept: [-0.32535836  1.91538302 -1.59002466]

True values:
[0 0 2 2 1 0 0 2 2 1 2 0 2 2 2 0 2 1 0 2 1 2 1 1 2 0 0 1 0 2]

Predict values:
[0 0 2 2 2 0 0 2 2 1 2 0 1 2 2 0 2 1 0 2 1 2 1 1 2 0 0 2 0 2]



In [84]:
print(f'Accuracy: {np.sum(y_test == y_pred1) / len(y_test)}')

Accuracy: 0.9


In [85]:
U, D, VT = np.linalg.svd(X)
U.shape, D.shape, VT.shape

((150, 150), (4,), (4, 4))

In [86]:
# return V
V = VT.T

In [87]:
# Get max values D (index, value)
D_max = np.array([[i, value] for i, value in enumerate(D) if D[i] > 10])

In [88]:
# create weights
indexes = D_max[:, 0].astype(np.int32)
values = D_max[:, 1]

W = V[:, indexes] * values
W

array([[ 10.90229629,  -4.41924555],
       [ -5.6355742 , -10.81102224],
       [ 12.14402126,  -0.28677632],
       [ 11.81853033,  -0.78383484]])

In [89]:
Z = X.dot(W)

In [90]:
# learning
X_train, X_test, y_train, y_test = train_test_split(Z, y, test_size=0.2, random_state=111)

log_model2 = LogisticRegression()
log_model2.fit(X_train, y_train)
y_pred = log_model2.predict(X_test)

print(f'Weight of model:\n{log_model2.coef_}\n')
print(f'Intercept: {log_model2.intercept_}\n')
print(f'True values:\n{y_test}\n')
print(f'Predict values:\n{y_pred}\n')

Weight of model:
[[-0.33153571 -0.04396155]
 [ 0.0410441   0.01008333]
 [ 0.29049162  0.03387822]]

Intercept: [-3.21421207  4.50597194 -1.29175987]

True values:
[0 0 2 2 1 0 0 2 2 1 2 0 2 2 2 0 2 1 0 2 1 2 1 1 2 0 0 1 0 2]

Predict values:
[0 0 2 2 2 0 0 2 2 1 2 0 2 2 2 0 2 1 0 2 1 2 1 1 2 0 0 1 0 2]



In [91]:
print(f'Accuracy: {np.sum(y_test == y_pred) / len(y_test)}')

Accuracy: 0.9666666666666667
