In [34]:
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [35]:
import tensorflow as tf
import numpy as np

In [36]:
print(tf.executing_eagerly())

True


#### Creating a tensor

### constant - immutable data

In [45]:
a = tf.constant(1)
print(a)  # value:1, rank=0, type: int32

tf.Tensor(1, shape=(), dtype=int32)


In [46]:
a = tf.constant(1, shape=(1, 1))
print(a)  # arr: [1], rank=2 (1row, 1col), type: int32

tf.Tensor([[1]], shape=(1, 1), dtype=int32)


In [47]:
b = tf.constant([1, 2, 3, 4, 5])
print(b)  # arr: [1, 2, 3, 4, 5], rank=1 (1row), type: int32,

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [48]:
b = tf.constant([[1, 2], [3, 4]], dtype=tf.float16)
print(b)  # arr: [[1, 2], [3, 4]], rank=2, type: float16

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float16)


#### Change the tensor type

In [49]:
b2 = tf.cast(b, dtype=tf.int32)
print(b2)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#### Transformation in Nampy

In [50]:
# Var 1
b_num_1 = np.array(b2)
print(b_num_1)

[[1 2]
 [3 4]]


In [51]:
b_num_2 = b2.numpy()
print(b_num_2)

[[1 2]
 [3 4]]


#### Variable - changeable data

In [54]:
v1 = tf.Variable(-1.2)
print(v1)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-1.2>


In [55]:
v2 = tf.Variable([1, 2, 3, 4], dtype=tf.float32)
print(v2)

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>


In [57]:
# create with exist constant
v3 = tf.Variable(b)
print(v3)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>


In [64]:
# overwrite values
# Note: size new = size old
v1.assign(3)  # overwrites values
print(v1)  # before: -1.2, after: 3.0

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>


In [68]:
# sum  tensors
print(f'Before: {v2}')
v2.assign_add([2, 2, 2, 2])
print(f'Afrer: {v2}')

Before: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>
Afrer: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([3., 4., 5., 6.], dtype=float32)>


In [69]:
# Subtractions tensors
print(f'Before: {v2}')
v2.assign_sub([3, 3, 3, 3])
print(f'After: {v2}')

Before: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([3., 4., 5., 6.], dtype=float32)>
After: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>


In [71]:
# shape
v2.shape

TensorShape([4])

In [73]:
# index
v2[1]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [74]:
v2[:3]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 2.], dtype=float32)>

In [81]:
copy_part_link = v2[1:3]
print(copy_part_link)  # this part of v2

# example change copy_part_link 
copy_part_link.assign([5, 5])
print(v2)
print(copy_part_link)

tf.Tensor([5. 5.], shape=(2,), dtype=float32)
<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 5., 5., 3.], dtype=float32)>
tf.Tensor([5. 5.], shape=(2,), dtype=float32)
