In [171]:
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [172]:
import tensorflow as tf
import numpy as np

In [173]:
print(tf.executing_eagerly())

True


#### Creating a tensor

### constant - immutable data

In [174]:
a = tf.constant(1)
print(a)  # value:1, rank=0, type: int32

tf.Tensor(1, shape=(), dtype=int32)


In [175]:
a = tf.constant(1, shape=(1, 1))
print(a)  # arr: [1], rank=2 (1row, 1col), type: int32

tf.Tensor([[1]], shape=(1, 1), dtype=int32)


In [176]:
b = tf.constant([1, 2, 3, 4, 5])
print(b)  # arr: [1, 2, 3, 4, 5], rank=1 (1row), type: int32,

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [177]:
b = tf.constant([[1, 2], [3, 4]], dtype=tf.float16)
print(b)  # arr: [[1, 2], [3, 4]], rank=2, type: float16

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float16)


#### Change the tensor type

In [178]:
b2 = tf.cast(b, dtype=tf.int32)
print(b2)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#### Transformation in Nampy

In [179]:
# Var 1
b_num_1 = np.array(b2)
print(b_num_1)

[[1 2]
 [3 4]]


In [180]:
b_num_2 = b2.numpy()
print(b_num_2)

[[1 2]
 [3 4]]


#### Variable - changeable data

In [181]:
v1 = tf.Variable(-1.2)
v1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-1.2>

In [182]:
v2 = tf.Variable([1, 2, 3, 4], dtype=tf.float32)
v2

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [183]:
# create with exist constant
v3 = tf.Variable(b)
v3

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [184]:
# overwrite values
# Note: size new = size old
v1.assign(3)  # overwrites values
v1  # before: -1.2, after: 3.0

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [185]:
# sum  tensors
print(f'Before: {v2}')
v2.assign_add([2, 2, 2, 2])
print(f'Afrer: {v2}')

Before: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>
Afrer: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([3., 4., 5., 6.], dtype=float32)>


In [186]:
# Subtractions tensors
print(f'Before: {v2}')
v2.assign_sub([3, 3, 3, 3])
print(f'After: {v2}')

Before: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([3., 4., 5., 6.], dtype=float32)>
After: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>


In [187]:
# shape
v2.shape

TensorShape([4])

In [188]:
# index
v2[1]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [189]:
v2[:3]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 2.], dtype=float32)>

In [190]:
copy_part_link = v2[1:3]
print(copy_part_link)  # this part of v2

# example change copy_part_link
copy_part_link.assign([5, 5])
print(v2)
print(copy_part_link) # save old values

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 5., 5., 3.], dtype=float32)>
tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [199]:
# gather
x = tf.constant(range(10)) + 5
x_indx = tf.gather(x ,[0, 4])  # create new tensor based on indexes of old tensor
print(x, x_indx, sep='\n')

tf.Tensor([ 5  6  7  8  9 10 11 12 13 14], shape=(10,), dtype=int32)
tf.Tensor([5 9], shape=(2,), dtype=int32)


In [205]:
#                          ↓
#               cols 0  1  2      rows
val1 = tf.constant([[1, 2, 0],  # 0
                    [3, 4, 66], # 1 ←
                    [5, 6, 2]]) # 2

val_indx = val1[1, 2]  # 1 row, 2 col in 1 arr
val_indx

<tf.Tensor: shape=(), dtype=int32, numpy=66>

In [206]:
val1[:, 2]  # all values in 2 cols

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 0, 66,  2])>

#### Change shape

In [209]:
a = tf.constant(range(30))
a

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])>

In [210]:
b = tf.reshape(a, [5, 6])
b

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])>

In [214]:
c = tf.reshape(a, [3, -1])  # 3 cols, 30/3 rows
print(c.numpy()) # numpy arr

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [216]:
c_T = tf.transpose(c)
c_T

<tf.Tensor: shape=(10, 3), dtype=int32, numpy=
array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29]])>

In [224]:
c_T2 = tf.transpose(c, perm=[0, 1])  # (optional) perm - indicates axis order
print(c_T2.numpy())

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
