In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [3]:
import tensorflow as tf
import numpy as np

#### Zeros

In [4]:
a_t = tf.zeros((3, 3))
a_t

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [5]:
a_n = np.zeros((3, 3))
print(a_n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
print(a_t.numpy())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Ones

In [7]:
b_t = tf.ones((2, 2))
b_t

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [8]:
b_n = np.ones((2, 2))
print(b_n)

[[1. 1.]
 [1. 1.]]


#### Ones_like

In [9]:
c_t = tf.ones_like(a_t)
c_t

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
c_n = np.ones_like(a_n)
print(c_n)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Zeros_like

In [11]:
d_t = tf.zeros_like(a_t)
d_t

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [12]:
d_n = np.zeros_like(a_n)
print(d_n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Eye

In [13]:
e_t = tf.eye(4)
e_t

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [14]:
e_n = np.eye(4)
print(e_n)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
e_t_2 = tf.eye(2, 3)
e_t_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.]], dtype=float32)>

In [16]:
e_n_2 = np.eye(2, 3)
print(e_n_2)

[[1. 0. 0.]
 [0. 1. 0.]]


### Identity

In [17]:
f_t = tf.identity(e_t_2)  # copy tensor
f_t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.]], dtype=float32)>

In [18]:
f_n = np.identity(4)  # create arr with 1 in main diagonal
print(f_n)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Fill

In [19]:
g_t = tf.fill((2, 3), -1)
g_t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]])>

In [20]:
arr = np.array([3, 3, 4])
arr.fill(35)
print(arr)

[35 35 35]


#### Range

In [21]:
h_t = tf.range(1, 10, 0.2)
print(h_t)

tf.Tensor(
[1.        1.2       1.4000001 1.6000001 1.8000002 2.0000002 2.2000003
 2.4000003 2.6000004 2.8000004 3.0000005 3.2000005 3.4000006 3.6000006
 3.8000007 4.0000005 4.2000003 4.4       4.6       4.7999997 4.9999995
 5.1999993 5.399999  5.599999  5.7999988 5.9999986 6.1999984 6.399998
 6.599998  6.799998  6.9999976 7.1999974 7.399997  7.599997  7.799997
 7.9999967 8.199997  8.399997  8.599997  8.799996  8.999996  9.199996
 9.399996  9.599996  9.799995 ], shape=(45,), dtype=float32)


In [22]:
h_n = np.arange(1, 10, 0.2)
print(h_n)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


### Random methods

#### Normal

In [25]:
# Normal distribution
a = tf.random.normal((2, 4), 0, 0.1)  # (2, 4) size, 0 - mathematical expectation, 0.1 - square deviation

In [27]:
a

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.0947099 , -0.02603861, -0.03615637, -0.07809832],
       [ 0.02157606,  0.13720022, -0.10385014,  0.0898334 ]],
      dtype=float32)>

In [28]:
# Uniform distribution
b = tf.random.uniform((2, 4), -1, 1)  # (2, 4) size, [-1, 1] range
b

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.69000936,  0.8548026 ,  0.56525993,  0.45419526],
       [ 0.19201899,  0.2652979 , -0.3716712 ,  0.9844582 ]],
      dtype=float32)>

In [29]:
# Set_seed
tf.random.set_seed(1)

In [31]:
# Truncated normal
c = tf.random.truncated_normal((1, 5), -1, 0.1)  # normal+-2sigma
c

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-1.110122  , -0.84542483, -0.9616356 , -1.0879657 , -0.85944796]],
      dtype=float32)>

In [36]:
# repeat with set_seed
tf.random.set_seed(1)
c = tf.random.truncated_normal((1, 5), -1, 0.1)  # normal+-2sigma
c

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-1.110122  , -0.84542483, -0.9616356 , -1.0879657 , -0.85944796]],
      dtype=float32)>

### Operations

In [42]:
# Tensors
a = tf.constant([1, 2, 3])
b = tf.constant([9, 8, 7])

# Numpy arrays
c = np.array([1, 2, 3])
d = np.array([9, 8, 7])

#### Sum

In [44]:
print(tf.add(a, b))
print(np.add(c, d))

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
[10 10 10]


In [45]:
print(a + b)
print(c + d)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
[10 10 10]


#### Subtraction

In [48]:
print(tf.subtract(b, a))
print(np.subtract(d, c))

tf.Tensor([8 6 4], shape=(3,), dtype=int32)
[8 6 4]


In [47]:
print(b - a)
print(d - c)

tf.Tensor([8 6 4], shape=(3,), dtype=int32)
[8 6 4]


#### Divide

In [52]:
print(tf.divide(b, a))
print(np.divide(d, c))

tf.Tensor([9.         4.         2.33333333], shape=(3,), dtype=float64)
[9.         4.         2.33333333]


In [53]:
print(b / a)
print(d / c)

tf.Tensor([9.         4.         2.33333333], shape=(3,), dtype=float64)
[9.         4.         2.33333333]


#### //

In [55]:
b // a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([9, 4, 2])>

In [57]:
print(d // c)

[9 4 2]


#### Multiply

In [58]:
print(tf.multiply(a, b))
print(np.multiply(c, d))

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
[ 9 16 21]


In [59]:
print(a * b)
print(c * d)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
[ 9 16 21]


#### Degree

In [60]:
a ** 2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [63]:
print(c ** 2)

[1 4 9]


#### Tensordot

In [64]:
tf.tensordot(a, b, axes=0)  # axes=0 important -> specifies on external multiplication

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]])>

In [71]:
print(np.outer(c, d)) # !!!

[[ 9  8  7]
 [18 16 14]
 [27 24 21]]


In [72]:
tf.tensordot(a, b, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [68]:
np.dot(c, d)

46

#### Matmul

In [73]:
a2 = tf.constant(tf.range(1, 10), shape=(3, 3))
b2 = tf.constant(tf.range(5, 14), shape=(3, 3))

In [74]:
tf.matmul(a2, b2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])>

In [77]:
c2 = np.array(np.arange(1, 10)).reshape(3, -1)
d2 = np.array(np.arange(5, 14)).reshape(3, -1)
print(np.matmul(c2, d2))

[[ 54  60  66]
 [126 141 156]
 [198 222 246]]


In [78]:
a2 @ b2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])>

In [81]:
print(c2 @ d2)

[[ 54  60  66]
 [126 141 156]
 [198 222 246]]


### Operations in matrix

In [82]:
m = tf.tensordot(a, b, axes=0)
m

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]])>

#### Reduce_sum

In [83]:
tf.reduce_sum(m)

<tf.Tensor: shape=(), dtype=int32, numpy=144>

In [84]:
tf.reduce_sum(m, axis=0) # sum columns

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([54, 48, 42])>

In [85]:
tf.reduce_sum(m, axis=1) # sum rows

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([24, 48, 72])>

In [86]:
n = np.outer(c, d)
n

array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]])

In [87]:
np.sum(n)

144

In [88]:
np.sum(n, axis=0)

array([54, 48, 42])

In [89]:
np.sum(n, axis=1)

array([24, 48, 72])

#### Mean

In [90]:
tf.reduce_mean(m)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [91]:
np.mean(n)

16.0

#### Max

In [92]:
tf.reduce_max(m)

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [93]:
tf.reduce_max(m, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 24, 21])>

In [94]:
tf.reduce_max(m, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 18, 27])>

In [95]:
np.max(n)

27

In [96]:
np.max(n, axis=0)

array([27, 24, 21])

In [97]:
np.max(n, axis=1)

array([ 9, 18, 27])

#### Min

In [98]:
tf.reduce_min(m)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [99]:
np.min(n)

7

#### Prod

In [101]:
tf.reduce_prod(m)  # multiply all values

<tf.Tensor: shape=(), dtype=int32, numpy=1883394048>

In [102]:
np.prod(n)

1883394048

In [103]:
tf.reduce_prod(m, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4374, 3072, 2058])>

In [104]:
np.prod(n, axis=0)

array([4374, 3072, 2058])

#### Sqrt

In [106]:
tf.sqrt(tf.cast(m, dtype=tf.float32))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[3.       , 2.828427 , 2.6457512],
       [4.2426405, 4.       , 3.7416575],
       [5.196152 , 4.8989797, 4.582576 ]], dtype=float32)>

In [107]:
np.sqrt(n)

array([[3.        , 2.82842712, 2.64575131],
       [4.24264069, 4.        , 3.74165739],
       [5.19615242, 4.89897949, 4.58257569]])

#### Square

In [108]:
tf.square(m)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 81,  64,  49],
       [324, 256, 196],
       [729, 576, 441]])>

In [109]:
np.square(n)

array([[ 81,  64,  49],
       [324, 256, 196],
       [729, 576, 441]])

#### Sin

In [112]:
tf.sin([np.pi, 0, 3.14])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-8.742278e-08,  0.000000e+00,  1.592548e-03], dtype=float32)>

In [113]:
np.sin([np.pi, 0, 3.14])

array([1.22464680e-16, 0.00000000e+00, 1.59265292e-03])