In [18]:
import tensorflow as tf

In [19]:
# 1
x = tf.Variable(-2.0)

In [20]:
with tf.GradientTape() as tape:
    y = x ** 2

df = tape.gradient(y, x)

In [21]:
print(df)

tf.Tensor(-4.0, shape=(), dtype=float32)


In [29]:
# 2
w = tf.Variable(tf.random.normal((3, 2)))
b = tf.Variable(tf.zeros(2, dtype=tf.float32))
x = tf.Variable([[-2.0, 1.0, 3.0]])

In [30]:
with tf.GradientTape() as tape:
    y = x @ w + b
    loss = tf.reduce_mean(y ** 2)

In [31]:
print(x.numpy())

[[-2.  1.  3.]]


In [32]:
print(w.numpy())

[[-1.4372045  -0.31241438]
 [-0.6689665  -1.1355852 ]
 [-1.0160764  -0.7184429 ]]


In [35]:
df = tape.gradient(loss, [w, b])
print(df[0], df[1], sep='\n')

tf.Tensor(
[[ 1.6855736  5.3321705]
 [-0.8427868 -2.6660852]
 [-2.5283604 -7.9982557]], shape=(3, 2), dtype=float32)
tf.Tensor([-0.8427868 -2.6660852], shape=(2,), dtype=float32)
