In [33]:
import tensorflow as tf

In [34]:
class DenseNN(tf.Module):
    def __init__(self, outputs):
        super().__init__()
        self.outputs = outputs
        self.fl_init = False

    def __call__(self, x):
        if not self.fl_init:
            self.w = tf.random.truncated_normal((x.shape[-1], self.outputs), stddev=0.1, name='w')  # limitation -> duble sigma
            self.b = tf.zeros([self.outputs], dtype=tf.float32, name='b')

            self.w = tf.Variable(self.w)
            self.b = tf.Variable(self.b)

            self.fl_init = True

        y = x @ self.w + self.b
        return y

In [35]:
model = DenseNN(1)

In [36]:
model(tf.constant([[1.0, 2.0]]))  # x = [1.0, 2.0]

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.16934119]], dtype=float32)>

In [37]:
x_train = tf.random.uniform(minval=0, maxval=10, shape=(100, 2))
y_train = [a + b for a, b in x_train]

In [38]:
x_train

<tf.Tensor: shape=(100, 2), dtype=float32, numpy=
array([[6.7075562 , 7.177241  ],
       [0.17211318, 5.313945  ],
       [6.021968  , 8.935842  ],
       [5.660921  , 1.5163982 ],
       [8.144116  , 8.790965  ],
       [9.683074  , 5.9124336 ],
       [5.9972334 , 1.7509174 ],
       [1.2156999 , 6.1575136 ],
       [0.40568233, 1.5517902 ],
       [4.388014  , 3.2653332 ],
       [8.349093  , 1.1356866 ],
       [5.450449  , 2.0785952 ],
       [8.738428  , 7.922344  ],
       [8.060447  , 6.1409197 ],
       [1.5412676 , 2.2234046 ],
       [1.8389618 , 0.87698936],
       [5.0382624 , 9.79084   ],
       [8.675331  , 7.845641  ],
       [1.6447508 , 3.1458354 ],
       [9.579029  , 7.1206164 ],
       [2.8983915 , 1.2696517 ],
       [7.38667   , 8.747263  ],
       [9.00577   , 2.0548475 ],
       [4.750793  , 5.353936  ],
       [1.0174704 , 6.993161  ],
       [7.9412737 , 8.017008  ],
       [9.838476  , 3.6449552 ],
       [1.3524699 , 7.6782503 ],
       [2.9299724 , 3.1277

In [39]:
loss = lambda x, y: tf.reduce_mean(tf.square(x - y))
opt = tf.optimizers.Adam(learning_rate=0.01)

In [40]:
EPOCHS = 50

for n in range(EPOCHS):
    for x, y in zip(x_train, y_train):
        x = tf.expand_dims(x, axis=0)
        y = tf.constant(y, shape=(1, 1))

        with tf.GradientTape() as t:
            f_loss = loss(y, model(x))

        grads = t.gradient(f_loss, model.trainable_variables)
        opt.apply_gradients(zip(grads, model.trainable_variables))

    print(f_loss.numpy())

16.966808
0.5164645
0.059774265
0.045563936
0.041354742
0.037199628
0.033104967
0.02914177
0.025367936
0.021828907
0.018561859
0.015596164
0.01294611
0.010618171
0.008604964
0.0068910886
0.0054532117
0.0042640883
0.0032936365
0.0025119542
0.0018904204
0.0014024903
0.0010243398
0.00073537126
0.0005178618
0.0003567384
0.00023966121
0.0001565076
9.892032e-05
6.0233146e-05
3.516427e-05
1.9581057e-05
1.0322911e-05
5.1344396e-06
2.3898256e-06
1.0315716e-06
4.094918e-07
1.4551915e-07
4.604317e-08
1.2028067e-08
2.4592737e-09
2.9467628e-10
1.4551915e-11
8.185452e-12
1.4551915e-11
8.185452e-12
9.094947e-13
9.094947e-13
9.094947e-13
0.0


In [41]:
print(model.trainable_variables)

(<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([3.249505e-06], dtype=float32)>, <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.9999998],
       [0.9999998]], dtype=float32)>)


In [42]:
print(model(tf.constant([[1.0, 2.0]])))

tf.Tensor([[3.0000029]], shape=(1, 1), dtype=float32)
