In [150]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow import keras

In [151]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [152]:
# Sequential - sets the sequence of layers
model = keras.Sequential([
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

In [153]:
model.layers

In [154]:
model.pop()  # delete last layer
model.layers

In [155]:
model.add(Dense(5, activation='linear'))  # add new layer
model.layers

In [156]:
# alternative
model2 = keras.Sequential()
model2.add(Dense(128, activation='relu', name='layer_1'))
model2.add(Dense(10, activation='linear', name='layer_2'))
model2.layers

In [157]:
model2.layers[0].weights

[]

In [158]:
x = tf.random.uniform((1, 20), 0, 1)
y = model2(x)
model2.layers[0].weights

[<tf.Variable 'layer_1/kernel:0' shape=(20, 128) dtype=float32, numpy=
 array([[ 0.00134265,  0.00377078,  0.18202439, ..., -0.0557963 ,
         -0.1120711 ,  0.12340009],
        [-0.19267748,  0.07435161, -0.11914086, ...,  0.11335978,
         -0.05289926,  0.19191161],
        [-0.10315046,  0.1350775 , -0.02697045, ..., -0.04096401,
         -0.04065567,  0.03296751],
        ...,
        [-0.08537979, -0.09750816,  0.17874077, ...,  0.11726949,
          0.096136  , -0.11807132],
        [ 0.08603045, -0.16947675, -0.14286566, ..., -0.13271105,
         -0.11358473,  0.02173485],
        [ 0.07655966, -0.11480685, -0.1539554 , ...,  0.11107796,
         -0.13046524,  0.17144763]], dtype=float32)>,
 <tf.Variable 'layer_1/bias:0' shape=(128,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [159]:
model2.summary()

Model: "sequential_39"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer_1 (Dense)             (1, 128)                  2688      
                                                                 
 layer_2 (Dense)             (1, 10)                   1290      
                                                                 
Total params: 3,978
Trainable params: 3,978
Non-trainable params: 0
_________________________________________________________________


In [160]:
model3 = keras.Sequential([
    Input(shape=(20,)),  # input layer
    Dense(128, activation='relu'),
    Dense(10, activation='linear')
])

model3.layers  # does not display the input layer

In [161]:
model4 = keras.Sequential([
    Dense(128, activation='relu', input_shape=(784,), name='hidden_1'),
    Dense(10, activation='softmax', name='output')
])

model4

In [162]:
model_ex = keras.Model(inputs=model4.inputs,
                       outputs=[layer.output for layer in model4.layers])

In [163]:
model_ex2 = keras.Model(
    inputs=model4.inputs,
    outputs=model4.get_layer(name='output').output)

In [164]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [165]:
x_train = x_train / 255
x_test = x_test / 255

In [166]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [167]:
x_train = tf.reshape(tf.cast(x_train, tf.float32), [-1, 28*28])
x_test = tf.reshape(tf.cast(x_test, tf.float32), [-1, 28*28])

y_train = to_categorical(y_train, 10)  # OneHot
y_test = to_categorical(y_test, 10)

In [168]:
model4.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [169]:
model4.fit(x_train, y_train, batch_size=32, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2582 - accuracy: 0.9261
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1119 - accuracy: 0.9674
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0761 - accuracy: 0.9772
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0572 - accuracy: 0.9829
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0432 - accuracy: 0.9865


In [170]:
x = tf.expand_dims(x_test[0], axis=0)
y = model_ex(x)
y2 = model4(x)
print(y, y2, sep='\n\n')

[<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[0.        , 0.        , 1.4238781 , 0.        , 2.1954603 ,
        0.        , 0.        , 0.6390693 , 0.        , 0.8275025 ,
        0.57632613, 0.        , 0.        , 0.        , 1.3017247 ,
        1.7533071 , 2.5934258 , 2.0810966 , 0.        , 1.538704  ,
        0.        , 3.931311  , 0.        , 0.4657364 , 0.        ,
        0.38632607, 1.1431984 , 0.06602136, 0.        , 0.79487824,
        0.        , 0.6407131 , 0.        , 0.        , 1.6442192 ,
        0.        , 4.106995  , 1.9005994 , 1.2728087 , 0.        ,
        1.73659   , 0.        , 0.        , 0.        , 0.        ,
        0.18008041, 1.3568149 , 0.        , 0.        , 3.5171206 ,
        1.7645018 , 0.        , 0.        , 0.7036338 , 0.        ,
        2.7253096 , 0.        , 0.        , 0.44000012, 0.        ,
        0.2189706 , 3.3007522 , 3.2434871 , 0.18436497, 0.        ,
        1.0613397 , 0.463547  , 0.        , 0.        , 1.5305058

In [171]:
model4.summary()

Model: "sequential_41"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_1 (Dense)            (None, 128)               100480    
                                                                 
 output (Dense)              (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [172]:
model_ex.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_1_input (InputLayer)  [(None, 784)]            0         
                                                                 
 hidden_1 (Dense)            (None, 128)               100480    
                                                                 
 output (Dense)              (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [173]:
model_ex2.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_1_input (InputLayer)  [(None, 784)]            0         
                                                                 
 hidden_1 (Dense)            (None, 128)               100480    
                                                                 
 output (Dense)              (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [174]:
model_ex3 = keras.Sequential([
    model4,  # integrated model
    Dense(10, activation='tanh')
])

In [176]:
# additional training model_ex3
model4.trainable = False

model_ex3.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model_ex3.fit(x_train, y_train, batch_size=32, epochs=3)

Epoch 1/3
1875/1875 [==============================] - 2s 1ms/step - loss: 7.8689 - accuracy: 0.3960
Epoch 2/3
1875/1875 [==============================] - 2s 1ms/step - loss: 9.9735 - accuracy: 0.3385
Epoch 3/3
1875/1875 [==============================] - 2s 1ms/step - loss: 11.1361 - accuracy: 0.3068


In [178]:
# partial ban of trainable model
model4.layers[0].trainable = False  # Choose layer and trainable=False