In [157]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [158]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [159]:
x_train = x_train.reshape(-1, 28*28) / 255
x_test = x_test.reshape(-1, 28*28) / 255

In [160]:
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [161]:
# model = keras.Sequential([
#     layers.Dense(128, activation='relu'),
#     layers.Dense(10, activation='softmax')
# ])

In [162]:
class NeuralNetwork(tf.keras.Model):
    def __init__(self, units):
        super().__init__()
        self.units = units
        self.model_layers = [layers.Dense(n, activation='relu') for n in self.units]

    def call(self, inputs):
        x = inputs
        for layer in self.model_layers:
            x = layer(x)

        return x

    def get_config(self):
        return {'units': self.units}

    @classmethod
    def from_config(cls, config):
        return cls(**config)

In [163]:
model = NeuralNetwork([128, 10])

In [164]:
y = model.predict(tf.expand_dims(x_test[0], axis=0))

1/1 [==============================] - 0s 153ms/step


In [165]:
model.save('save/model_1')

INFO:tensorflow:Assets written to: save/model_1\assets


In [166]:
model_loaded = keras.models.load_model('save/model_1')

In [167]:
model_loaded

In [168]:
y = model_loaded.predict(tf.expand_dims(x_test[0], axis=0))
y

1/1 [==============================] - 0s 58ms/step


array([[0.        , 0.07022312, 0.04562209, 0.14030099, 0.        ,
        0.40295482, 0.34250838, 0.        , 0.0259437 , 0.34894812]],
      dtype=float32)

In [169]:
class NeuralNetworkLinear(tf.keras.Model):
    def __init__(self, units):
        super().__init__()
        self.units = units
        self.model_layers = [layers.Dense(n, activation='linear') for n in units]

    def call(self, inputs):
        x = inputs
        for layer in self.model_layers:
            x = layer(x)

        return x

    def get_config(self):
        return {'units': self.units}

    @classmethod
    def from_config(cls, config):
        return cls(**config)

In [170]:
model_loaded_2 = keras.models.load_model('save/model_1', custom_objects={'NeuralNetwork': NeuralNetworkLinear})

In [171]:
y = model_loaded_2.predict(tf.expand_dims(x_test[0], axis=0))
y

1/1 [==============================] - 0s 54ms/step


array([[-0.46161696,  0.52683246, -0.00715706,  0.1541865 ,  0.5825513 ,
        -0.07443477,  0.26353434, -0.023154  , -0.15951085,  0.43611082]],
      dtype=float32)

In [172]:
#model.compile(optimizer=keras.optimizers.Adam(), loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])

In [173]:
#model.fit(x_train, y_train, epochs=3)

#### Save

#### Load

In [174]:
#model_loaded.evaluate(x_test, y_test)

In [175]:
model2 = NeuralNetwork([128, 10])

In [176]:
y = model.predict(tf.expand_dims(x_test[0], axis=0))
y2 = model2.predict(tf.expand_dims(x_test[0], axis=0))
y

1/1 [==============================] - 0s 135ms/step


array([[0.        , 0.07022312, 0.04562209, 0.14030099, 0.        ,
        0.40295482, 0.34250838, 0.        , 0.0259437 , 0.34894812]],
      dtype=float32)

In [177]:
y2

array([[0.11897676, 0.49748555, 0.        , 0.35500154, 0.15788542,
        0.        , 0.        , 0.        , 0.        , 0.2599619 ]],
      dtype=float32)

In [178]:
weights = model.get_weights()

In [179]:
model2.set_weights(weights)

In [180]:
y2 = model2.predict(tf.expand_dims(x_test[0], axis=0))
y2

1/1 [==============================] - 0s 23ms/step


array([[0.        , 0.07022312, 0.04562209, 0.14030099, 0.        ,
        0.40295482, 0.34250838, 0.        , 0.0259437 , 0.34894812]],
      dtype=float32)

In [181]:
model.save_weights('save/weights')
model2.load_weights('save/weights')

In [183]:
y3 = model2.predict(tf.expand_dims(x_test[0], axis=0))
y3

1/1 [==============================] - 0s 24ms/step


array([[0.        , 0.07022312, 0.04562209, 0.14030099, 0.        ,
        0.40295482, 0.34250838, 0.        , 0.0259437 , 0.34894812]],
      dtype=float32)