In [1]:
import numpy as np

### умножение матриц

$X1(число\ столбцов) = X2(число\ строк)$

In [10]:
X1 = np.array([[1, 2],
               [3, 4],
               [5, 6]])

X2 = np.array([[7, 8, 9, 10],
               [11, 12, 13, 14]])

In [11]:
X1.shape[1] == X2.shape[0]

True

In [12]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [13]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [14]:
Z.shape

(3, 4)

Пример расчета: Получение Z[0, 0]:

In [15]:
X1[0, 0] * X2[0, 0] + X1[0, 1] * X2[1, 0]

29

Пример расчета: Получение Z[1, 1]:

In [16]:
X1[1, 0] * X2[0, 1] + X1[1, 1] * X2[1, 1]

72

### модуль numpy.linalg: возведение матрицы в квадрат

In [17]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [19]:
A_square = np.dot(A, A)
A_square

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [20]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### создание единичной матрицы

In [27]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]]) # 3 x 2

In [28]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [29]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [30]:
np.dot(A, I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### транспонирование матрицы

In [32]:
A = np.array([[11, 12],
              [13, 14],
              [15, 16]])

In [34]:
At = A.transpose()
At

array([[11, 13, 15],
       [12, 14, 16]])

In [35]:
A.T

array([[11, 13, 15],
       [12, 14, 16]])

Рассмотрим матрицы X и Y:

In [37]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [38]:
Y = np.array([[0, 1],
              [3, 4],
              [6, 7],
              [2, 5]])

In [39]:
Yt = Y.T
Yt

array([[0, 3, 6, 2],
       [1, 4, 7, 5]])

In [40]:
np.dot(X, Yt)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

### вычисление определителя и ранга матрицы

пример 1:

In [41]:
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

определитель

In [42]:
np.linalg.det(A)

0.0

ранг

In [45]:
np.linalg.matrix_rank(A)

2

пример 2:

In [47]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

определитель

In [54]:
#np.linalg.det(A) # error: Last 2 dimensions of the array must be square

ранг

In [50]:
np.linalg.matrix_rank(A)

2

### вычисление обратной матрицы

In [51]:
B = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

обратная матрица B:

In [53]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

свойство обратной матрицы

In [60]:
B_inv2 = np.linalg.inv(B_inv)
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])