In [1]:
import numpy as np

In [6]:
a = np.random.randint(0, 20, 10)
a

array([ 0, 18,  4, 10,  6, 17, 16, 19, 13,  8])

In [7]:
a[a > 10]

array([18, 17, 16, 19, 13])

In [8]:
a[(a > 10) & (a % 2 == 0)]

array([18, 16])

In [15]:
a[(a > 7) & (a % 2 == 0)]

array([18, 10, 16,  8])

### numpy.where

1) получение индексов по условию

In [16]:
np.where(a > 10)

(array([1, 5, 6, 7, 8], dtype=int64),)

In [17]:
a[np.where(a > 10)]

array([18, 17, 16, 19, 13])

2) маска (True -> значение из первого массива, False -> значение из второго массива)

In [18]:
a = [1, 4, 7]
b = [9, 2, 5]

In [19]:
np.where([True, False, True], a, b)

array([1, 2, 7])

### Сортировка

In [20]:
a = np.array([[1, 4, 2, 6],
              [5, 3, 7, 2],
              [2, 3, 1, 6]])

In [22]:
a[[0, 2, 1], :]

array([[1, 4, 2, 6],
       [2, 3, 1, 6],
       [5, 3, 7, 2]])

In [23]:
a.argsort(axis=0)

array([[0, 1, 2, 1],
       [2, 2, 0, 0],
       [1, 0, 1, 2]], dtype=int64)

In [24]:
a[:, 0].argsort(axis=0)

array([0, 2, 1], dtype=int64)

In [25]:
a[a[:, 0].argsort(axis=0), :]

array([[1, 4, 2, 6],
       [2, 3, 1, 6],
       [5, 3, 7, 2]])

### Перемешивание

In [28]:
a = np.arange(10)

In [31]:
np.random.shuffle(a)
a

array([5, 9, 4, 0, 3, 7, 2, 8, 1, 6])

### Математичесткие действия

Применение математических действий ко всему массиву

In [34]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

логарифм по снованию e

In [36]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

экспонента

In [37]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

сумма всех элементов

In [38]:
a.sum()

21

сумма по столбцам

In [39]:
a.sum(axis=0)

array([5, 7, 9])

сумма по строкам

In [40]:
a.sum(axis=1)

array([ 6, 15])

поэлементоное умножение значений матриц

In [42]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
b = np.arange(9, 0, -1).reshape(3, 3)
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [44]:
a * b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

Broadcasting (на примере сложения)

сложение матриц разных размеров

1) совпадает число столбцов

In [45]:
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])

In [46]:
b = np.array([1, 2])

В этом случае к каждой строке a будет добавлен массив b

In [47]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

2) совпадает число строк

In [51]:
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])

In [52]:
b = np.array([[1],
              [4],
              [2]])

В этом случае к каждому столбцу a будет добавлен массив b

In [54]:
a + b

array([[3, 6],
       [7, 8],
       [8, 3]])

### статистичесткие функции

In [56]:
a = np.random.randint(0, 12, (3, 4))
a

array([[ 2,  4,  2,  6],
       [ 3,  0, 11,  5],
       [11,  4,  8,  6]])

минимальное значение

In [57]:
a.min()

0

минимальное значение для каждого столбца

In [58]:
a.min(axis=0)

array([2, 0, 2, 5])

минимальное значение для каждой строки

In [59]:
a.min(axis=1)

array([2, 0, 4])

максимальное значение (аналогично)

In [60]:
a.max(axis=1)

array([ 6, 11, 11])

среднее значение

In [61]:
a.mean(axis=0)

array([5.33333333, 2.66666667, 7.        , 5.66666667])

стреднее квадратичное отклонение

In [62]:
a.std(axis=1)

array([1.6583124 , 4.02336923, 2.58602011])

### Запись и чтение массива из файла

In [63]:
np.save('a.npy', a)

In [64]:
b = np.load('a.npy')

In [65]:
b

array([[ 2,  4,  2,  6],
       [ 3,  0, 11,  5],
       [11,  4,  8,  6]])