In [1]:
import numpy as np

### автоматическое создание массивов

In [3]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
b = np.ones((3, 4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 10, 0.5) # третий аргумент указывает на шаг дисктретности в массиве

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

In [15]:
np.linspace(0, 10, 11) # третий аргумент указывает на количество  элементов в массиве
# второе число включительно в  linspace в отличие от arange

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.logspace(0, 2, 3) # 10^0, 10^1, 10^2 => 3 числа

array([  1.,  10., 100.])

### генерация случайных чисел

In [22]:
np.random.sample()

0.2929268541938943

In [23]:
np.random.sample(3)

array([0.09762929, 0.86908234, 0.25799764])

In [24]:
np.random.sample((2, 3))

array([[0.78675041, 0.06846467, 0.66374318],
       [0.76414398, 0.67177141, 0.04201355]])

пример вывода случайной картинки: np.random.sample(x, y, z) x: строки, y: столбцы, z: цвет пикселя(RGB)

In [26]:
np.random.sample((5, 6, 3))

array([[[0.94716438, 0.5839734 , 0.54170677],
        [0.86054951, 0.78486385, 0.32004669],
        [0.83005425, 0.41621277, 0.27931147],
        [0.45731944, 0.61597197, 0.16261681],
        [0.6104609 , 0.84044699, 0.16076838],
        [0.61546251, 0.12973284, 0.97179801]],

       [[0.85761897, 0.71601467, 0.75121786],
        [0.4280673 , 0.94320058, 0.85453341],
        [0.19863847, 0.11282953, 0.8568959 ],
        [0.44477739, 0.9229075 , 0.66453067],
        [0.97633104, 0.07469193, 0.54802463],
        [0.37017903, 0.3436161 , 0.14139661]],

       [[0.98611119, 0.23750168, 0.60657265],
        [0.5006431 , 0.28811813, 0.14640526],
        [0.62514376, 0.23113575, 0.8163348 ],
        [0.6845519 , 0.24313321, 0.5832974 ],
        [0.07105931, 0.49195765, 0.0877005 ],
        [0.96582319, 0.4519443 , 0.21424697]],

       [[0.98948792, 0.0238487 , 0.25866891],
        [0.10909286, 0.97968105, 0.38520707],
        [0.63430452, 0.37232814, 0.05311456],
        [0.8405509 , 0.99706

### случайные числа с нормальным распределением

In [27]:
np.random.randn(10)

array([ 0.82463456,  1.09567441,  0.97036853, -0.03023433, -0.1992592 ,
        0.50593813,  0.1351298 , -0.09894123,  0.44442799, -2.97749336])

In [28]:
np.random.randn(3, 4)

array([[ 1.0158324 ,  0.47889012,  1.30751484,  0.51615908],
       [ 1.63231541, -0.33133061, -0.20928891,  0.68568376],
       [-0.09795696,  0.2562013 , -1.95900444, -0.21824378]])

### массив из случайных целых чисел

In [30]:
np.random.randint(0, 100, 10) # невключительно 100

array([67, 76, 85, 11, 60, 51, 17, 60, 61, 49])

In [31]:
np.random.randint(0, 100, (3, 4))

array([[85, 41, 74, 96],
       [49, 70, 65, 57],
       [56, 90,  4,  0]])

### получение случайных элементов из массива

In [32]:
b = np.array([4, 2, 6, 8, 3, 1, 0, 9, 7])

In [33]:
np.random.choice(b)

6

In [34]:
np.random.choice(b, 3)

array([8, 1, 6])

### инициализатор случайных чисел

In [35]:
np.random.seed(42)
np.random.rand()

0.3745401188473625

In [36]:
np.random.seed(42)
np.random.rand()

0.3745401188473625

### изменение формы массива

In [38]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

автоматическое расчет количества столбцов или строк

In [40]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

изменение самого массива

In [45]:
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

получение одномерного массива

In [49]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### соединение массивов

In [51]:
a = np.zeros((3, 4))
b = np.ones((3, 4))

In [52]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

соединение строк

In [55]:
v = np.vstack((a, b))
v

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
np.concatenate((a, b), axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

соединение столбцов

In [59]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [61]:
np.concatenate((a, b), axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

соединение в глубину (в третьем измерении)

In [62]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])