In [1]:
import numpy as np

In [6]:
a = np.random.randint(0, 20, 10)
a

array([ 0, 18,  4, 10,  6, 17, 16, 19, 13,  8])

In [7]:
a[a > 10]

array([18, 17, 16, 19, 13])

In [8]:
a[(a > 10) & (a % 2 == 0)]

array([18, 16])

In [15]:
a[(a > 7) & (a % 2 == 0)]

array([18, 10, 16,  8])

### numpy.where

1) получение индексов по условию

In [16]:
np.where(a > 10)

(array([1, 5, 6, 7, 8], dtype=int64),)

In [17]:
a[np.where(a > 10)]

array([18, 17, 16, 19, 13])

2) маска (True -> значение из первого массива, False -> значение из второго массива)

In [18]:
a = [1, 4, 7]
b = [9, 2, 5]

In [19]:
np.where([True, False, True], a, b)

array([1, 2, 7])

### Сортировка

In [20]:
a = np.array([[1, 4, 2, 6],
              [5, 3, 7, 2],
              [2, 3, 1, 6]])

In [22]:
a[[0, 2, 1], :]

array([[1, 4, 2, 6],
       [2, 3, 1, 6],
       [5, 3, 7, 2]])

In [23]:
a.argsort(axis=0)

array([[0, 1, 2, 1],
       [2, 2, 0, 0],
       [1, 0, 1, 2]], dtype=int64)

In [24]:
a[:, 0].argsort(axis=0)

array([0, 2, 1], dtype=int64)

In [25]:
a[a[:, 0].argsort(axis=0), :]

array([[1, 4, 2, 6],
       [2, 3, 1, 6],
       [5, 3, 7, 2]])

### Перемешивание

In [28]:
a = np.arange(10)

In [31]:
np.random.shuffle(a)
a

array([5, 9, 4, 0, 3, 7, 2, 8, 1, 6])