In [1]:
import numpy as np

In [6]:
a = [i for i in range(10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
c = tuple(a)
b = np.array(c)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
type(b)

numpy.ndarray

In [33]:
b = np.array(a, dtype=float)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
b[0]

0

In [34]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
b = np.array(b, dtype=int)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
b.ndim

1

In [38]:
b.shape

(10,)

In [52]:
x = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
              [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [53]:
x.ndim

2

In [54]:
x.shape

(3, 10)

In [57]:
x[1, 4]

14

In [61]:
x[0:2, 0:6]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

In [62]:
x[:2, :6]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

In [69]:
x[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [70]:
c = b.copy()

In [72]:
c[0] = 11
c == b

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])