In [17]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

A = np.array([
    [1.0, 2.0, -1.0],
    [2.0, 2.0, 5.0],
    [-1.0, 5.0, -3.0]
])

In [14]:
v, w = np.linalg.eigh(A)

In [18]:
v

array([-6.58,  1.15,  5.43])

In [19]:
w

array([[-0.25,  0.93, -0.27],
       [ 0.53, -0.11, -0.84],
       [-0.81, -0.35, -0.47]])

In [20]:
D = np.diag(v)

In [21]:
D

array([[-6.58,  0.  ,  0.  ],
       [ 0.  ,  1.15,  0.  ],
       [ 0.  ,  0.  ,  5.43]])

In [22]:
S = w.T

In [23]:
S

array([[-0.25,  0.53, -0.81],
       [ 0.93, -0.11, -0.35],
       [-0.27, -0.84, -0.47]])

In [24]:
S.T

array([[-0.25,  0.93, -0.27],
       [ 0.53, -0.11, -0.84],
       [-0.81, -0.35, -0.47]])

In [25]:
np.dot(S.T, S)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.dot(S, S.T)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.dot(np.dot(S.T, D), S)

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])