In [256]:
import torch

In [257]:
# create empty tensor
x = torch.empty(2, 3)
x

tensor([[2.6728e+23, 2.6952e-09, 4.3917e-05],
        [2.1590e-04, 1.0812e-05, 1.0781e-08]])

In [258]:
# tensor with values = 1
y = torch.ones(2, 3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [259]:
# type of values in tensor
y.dtype

torch.float32

In [260]:
# torch.float16, torch.double and etc.
z = torch.ones(2, 3, dtype=torch.double)
z

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [261]:
# size of tensor
z.size()

torch.Size([2, 3])

In [262]:
# tensor with yourself values
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

In [263]:
# random values in tensor
y = torch.rand(2, 2)
y

tensor([[0.5079, 0.9846],
        [0.0195, 0.6123]])

In [264]:
# x + y
z = x + y
z = torch.add(x, y)
z

tensor([[3.0079, 1.0846],
        [2.5195, 0.7123]])

In [265]:
# y = y + x
y.add_(x)

tensor([[3.0079, 1.0846],
        [2.5195, 0.7123]])

In [266]:
# y - x
z = y - x
z = torch.sub(y, x)
z

tensor([[0.5079, 0.9846],
        [0.0195, 0.6123]])

In [267]:
# y * x
z = x * y
z = torch.mul(x, y)
z

tensor([[7.5197, 0.1085],
        [6.2987, 0.0712]])

In [268]:
#  y / x
z = torch.div(y, x)
z

tensor([[ 1.2032, 10.8455],
        [ 1.0078,  7.1228]])

In [269]:
# operations of splice/split tensors
x = torch.rand(5, 3)
x

tensor([[0.5761, 0.8491, 0.0650],
        [0.5215, 0.2147, 0.0073],
        [0.9570, 0.7983, 0.0954],
        [0.8970, 0.4063, 0.9746],
        [0.6146, 0.1520, 0.7731]])

In [270]:
# [all row, zero col]
x[:, 0]

tensor([0.5761, 0.5215, 0.9570, 0.8970, 0.6146])

In [271]:
# [1 row, all col]
x[1, :]

tensor([0.5215, 0.2147, 0.0073])

In [272]:
# [1 col, 1 row]
x[1, 1]

tensor(0.2147)

In [273]:
# exact value
x[1, 1].item()

0.21467983722686768

In [274]:
x = torch.rand(4, 4)
print('x tensor: \n', x, '\n')
y = x.view(16)
print('x reshape tesor: \n', y)

x tensor: 
 tensor([[0.7808, 0.0639, 0.1366, 0.9320],
        [0.5285, 0.7785, 0.5187, 0.4128],
        [0.1462, 0.6072, 0.0365, 0.4997],
        [0.2783, 0.2442, 0.7318, 0.1606]]) 

x reshape tesor: 
 tensor([0.7808, 0.0639, 0.1366, 0.9320, 0.5285, 0.7785, 0.5187, 0.4128, 0.1462,
        0.6072, 0.0365, 0.4997, 0.2783, 0.2442, 0.7318, 0.1606])


In [275]:
# also: [2, 8], (2, 8)
y = x.view(2, 8)
y

tensor([[0.7808, 0.0639, 0.1366, 0.9320, 0.5285, 0.7785, 0.5187, 0.4128],
        [0.1462, 0.6072, 0.0365, 0.4997, 0.2783, 0.2442, 0.7318, 0.1606]])

In [276]:
# -1 -> missing quantity
y = x.view(2, -1)
y

tensor([[0.7808, 0.0639, 0.1366, 0.9320, 0.5285, 0.7785, 0.5187, 0.4128],
        [0.1462, 0.6072, 0.0365, 0.4997, 0.2783, 0.2442, 0.7318, 0.1606]])

In [277]:
print(y.size())

torch.Size([2, 8])


In [278]:
# numpy transformation
import numpy as np

In [279]:
# use GPU cuda => memory cell (in GPU)
cuda0 = torch.device('cuda:0')
a = torch.ones(5, device=cuda0)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.], device='cuda:0')
<class 'torch.Tensor'>


In [280]:
# use CPU convert numpy => other memory cell (in CPU)
b = a.detach().cpu().numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [281]:
# if torch and numpy in CPU -> link on one memory cell => a = a + 2 = b + 2
print(a.add_(1))
print(b)

tensor([2., 2., 2., 2., 2.], device='cuda:0')
[1. 1. 1. 1. 1.]


In [282]:
# if use only CPU => one link on one cell (torch and numpy)
c = torch.ones(5)
print(c)
d = c.numpy()
print(d)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [283]:
# c+1 = d+1 => (torch + 1) = (numpy + 1)
print(c.add_(1))
print(d)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [284]:
# convert numpy to torch
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [286]:
# one memory cell
a += 1
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [287]:
# test on access cuda GPU
torch.cuda.is_available()  # True => we can use GPU

True

In [292]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)  # 1 variant
    print(x)
    y = torch.ones(5)
    y = y.to(device) # 2 variant
    print(y)
    z = x + y
    print(z)
    z = z.to('cpu')
    print(z)
    z = z.numpy()
    print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([2., 2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [293]:
# if need gradient = True (temporary pass)
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
