In [98]:
import torch
import numpy as np

In [99]:
x = torch.randn(3, requires_grad=True)
x

tensor([-1.7909,  0.3317,  0.8817], requires_grad=True)

In [100]:
y = x + 2
y

tensor([0.2091, 2.3317, 2.8817], grad_fn=<AddBackward0>)

In [101]:
z = y * y * 2
# z = z.mean()
# z

In [102]:
# dz/dx
# z.backward()
# x.grad

In [103]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)

In [104]:
z.backward(v)
x.grad

tensor([0.0836, 9.3268, 0.0115])

In [105]:
# Variants requires_grad => OFF

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad()

In [106]:
# Variant 1. requires_grad => OFF
x.requires_grad_(False)
print(x)

tensor([-1.7909,  0.3317,  0.8817])


In [107]:
# Variant 2. requires_grad => OFF
y = torch.randn([3], requires_grad=True)
print(y)
y = x.detach()
print(y)

tensor([-0.2715,  0.0951,  0.4189], requires_grad=True)
tensor([-1.7909,  0.3317,  0.8817])


In [108]:
# Variant 3. requires_grad => OFF
x = torch.randn(3, requires_grad=True)
print(x)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([-0.0075,  1.2659,  1.3389], requires_grad=True)
tensor([1.9925, 3.2659, 3.3389])


In [109]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)
    print(weights.grad.zero_())

tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])
tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])
tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])


In [110]:
# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step()
# optimizer.zero_grad()