In [12]:
import torch
from torch.utils.data import Dataset
import numpy as np
import torchvision

In [13]:
# dataset = torchvision.datasets.MNIST(
#     root='./data', transform=torchvision.transforms.ToTensor())

In [14]:
class WineDataset(Dataset):
    def __init__(self, transform=None):
        xy = np.loadtxt('data/wine.csv', delimiter=',', skiprows=1, dtype=np.float32)

        self.n_samples = xy.shape[0]

        self.x = xy[:, 1:]
        self.y = xy[:, [0]]

        self.transform = transform

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]

        # if transform (not None)
        if self.transform:
            sample = self.transform(sample)

        return sample

    def __len__(self):
        return self.n_samples

In [15]:
class ToTensor:
    # Convert sample numpy to tensor
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [24]:
class MulTranform:
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor

        return inputs, targets

In [26]:
# transform=ToTensor() => torch.tensor; transform=None => numpy.array
dataset_1 = WineDataset(transform=ToTensor())
first_data = dataset_1[0]
first_data

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [27]:
#  compose several transformations (e.g. MulTransform => inputs * 2; ToTensor => convert to torch)
composed = torchvision.transforms.Compose([ToTensor(), MulTranform(2)])

dataset_2 = WineDataset(transform=composed)
first_data = dataset_2[0]
first_data

(tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
         6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
         2.1300e+03]),
 tensor([1.]))

In [19]:
features, labels = first_data

In [22]:
print(type(features), type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>
