In [2]:
import torch

In [3]:
x = torch.randn([1, 100, 3])
x

tensor([[[-0.9832,  0.2289,  0.0030],
         [-0.3075, -0.8232, -0.8935],
         [ 0.4590,  0.6156, -1.7462],
         [ 0.5476, -0.9390,  0.2995],
         [ 0.1760, -0.2635, -0.0683],
         [-0.5477, -1.1418, -0.1487],
         [-0.9617, -1.4912, -1.1885],
         [-0.8039, -0.1008, -0.7365],
         [ 0.8840,  1.6802, -0.7624],
         [-0.5667,  0.1438,  1.7984],
         [-0.4737,  0.1168, -0.4407],
         [-0.4961,  1.2261,  1.6246],
         [-1.0901, -0.7626,  1.4355],
         [ 0.3894,  1.8175,  0.2566],
         [ 0.2822, -0.4133, -1.8052],
         [ 1.1450, -0.1435,  0.0544],
         [-0.2028,  0.9606, -0.3248],
         [ 0.6722, -0.7744, -1.2998],
         [-0.6087,  0.1511, -1.5150],
         [ 2.1111,  0.0637,  0.0162],
         [ 0.1926,  0.0239, -0.1330],
         [ 0.2024, -0.9956, -1.0003],
         [ 1.3501,  0.2846, -0.9154],
         [-0.7812,  0.1294,  0.5202],
         [ 0.5386, -0.1719, -1.0349],
         [-0.3751,  0.4309, -2.0398],
         [-1

In [4]:
target = torch.randn([1, 100, 64])
target

tensor([[[-0.7238,  0.2395,  0.0466,  ...,  0.0261,  0.4437, -1.2984],
         [ 0.0358,  0.5707,  0.3774,  ...,  0.5828,  0.3913, -1.2695],
         [-0.6184,  0.2755, -1.4100,  ..., -0.4424,  0.0999, -0.1902],
         ...,
         [-0.7221,  0.1553,  0.6805,  ...,  0.2177, -0.4067, -0.0808],
         [-0.4371,  1.2959, -0.7421,  ...,  0.0724, -0.7296,  1.1174],
         [ 1.3635,  0.2777,  1.8447,  ..., -1.7175, -0.5901,  1.0601]]])

In [5]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(3, 64)

    def forward(self, x):
        x = self.fc1(x)
        return x

In [6]:
model = Net()

In [7]:
model(x)

tensor([[[ 0.6111,  0.8772,  0.8255,  ...,  0.6927,  0.2047,  0.5415],
         [ 0.0570,  0.4852,  0.0920,  ..., -0.1383,  0.1868, -0.1701],
         [-0.7213,  1.1764,  0.5688,  ..., -0.7212, -0.9583, -0.0718],
         ...,
         [ 0.1140,  1.1973,  0.9909,  ...,  0.2773, -0.4521,  0.4999],
         [ 0.5428,  1.5595,  1.4281,  ...,  0.6014,  0.3824,  1.0309],
         [ 0.3509,  0.3079,  0.0248,  ...,  0.1406,  0.4950, -0.1292]]],
       grad_fn=<ViewBackward0>)

In [8]:
model(x).shape

torch.Size([1, 100, 64])

In [9]:
criterion = torch.nn.MSELoss()

In [10]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.0003)

In [11]:
for epoch in range(10):
    output = model(x)
    loss = criterion(output, target)
    print('Epoch: ', epoch, 'Loss: ', loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch:  0 Loss:  1.4175866842269897
Epoch:  1 Loss:  1.4175786972045898
Epoch:  2 Loss:  1.4175705909729004
Epoch:  3 Loss:  1.4175626039505005
Epoch:  4 Loss:  1.417554497718811
Epoch:  5 Loss:  1.4175463914871216
Epoch:  6 Loss:  1.4175384044647217
Epoch:  7 Loss:  1.4175301790237427
Epoch:  8 Loss:  1.4175220727920532
Epoch:  9 Loss:  1.4175142049789429
