In [2]:
import torch

In [3]:
x = torch.randn([1, 100, 3])
x

tensor([[[-1.1325, -0.3373,  0.0368],
         [-1.1287,  0.6922,  1.1113],
         [ 0.3989, -0.5943,  0.5351],
         [-1.9194,  0.5905, -2.1775],
         [ 0.5213, -1.7569, -1.5484],
         [ 1.0530, -0.1698,  0.6860],
         [-0.4110,  0.2683, -0.9100],
         [ 1.6358, -1.3182,  2.0756],
         [-1.8096, -1.4221, -1.3069],
         [-1.3002, -0.8243,  0.1949],
         [-0.7855,  1.2647,  0.3581],
         [-1.5184,  1.2282, -0.1411],
         [ 0.4189, -0.7866, -0.3628],
         [-0.3555,  1.0557,  0.7161],
         [-0.8924, -0.5293,  0.4849],
         [ 0.4057,  0.6159,  3.0996],
         [ 2.5404,  0.4531,  0.5737],
         [-1.1499,  1.7162,  1.3199],
         [-1.3470,  0.2231, -0.1059],
         [ 0.8992,  1.5280, -1.2658],
         [-1.5912,  1.1797,  0.3259],
         [ 0.9177, -2.4947, -0.4917],
         [-0.6663,  0.7507, -1.0276],
         [-0.9553,  0.2540, -1.0182],
         [ 0.6959,  0.9348,  0.1801],
         [ 1.4611,  1.1868,  1.2068],
         [ 0

In [4]:
target = torch.randn([1, 100, 64])
target

tensor([[[-0.7719,  0.0549, -0.1750,  ..., -1.3300, -0.7007,  0.5914],
         [ 1.5952,  1.5033, -1.1244,  ..., -0.1512,  0.4053,  0.6365],
         [-0.3734,  0.3780, -0.5857,  ...,  0.6597,  0.5376,  0.4337],
         ...,
         [ 1.1505,  1.3911,  0.1294,  ..., -2.0700,  2.2913,  1.8522],
         [ 2.1904,  0.6156,  1.5826,  ...,  0.2273,  2.7715, -0.7861],
         [ 1.4541,  1.2468,  0.6096,  ..., -0.0254, -1.7783,  0.1679]]])

In [5]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(3, 64)  # w*x+b, w - weight, b - bias

    def forward(self, x):  # __call__ -> forward()
        x = self.fc1(x)
        return x

In [6]:
model = Net()

In [13]:
model(x)

tensor([[[ 0.1300, -0.4374, -0.2455,  ...,  0.8409, -0.4022, -0.2514],
         [ 0.8081, -1.2565, -0.6364,  ...,  0.2674, -1.0874, -1.0255],
         [ 0.8648, -0.2718, -0.2358,  ...,  0.0800,  0.3331, -0.3003],
         ...,
         [ 0.7806, -0.1691, -0.1629,  ..., -0.3242,  0.3747, -0.3008],
         [-0.3772, -0.0128, -0.0039,  ...,  0.7667, -0.2033,  0.0784],
         [ 0.1820, -0.5237, -0.2857,  ...,  0.8096, -0.4868, -0.3264]]],
       grad_fn=<ViewBackward0>)

In [15]:
parameters = list(model.parameters())

In [16]:
parameters[0].shape

torch.Size([64, 3])

In [17]:
x.shape

torch.Size([1, 100, 3])

wx+b

In [18]:
x.matmul(parameters[0].T) + parameters[1]

tensor([[[ 0.1300, -0.4374, -0.2455,  ...,  0.8409, -0.4022, -0.2514],
         [ 0.8081, -1.2565, -0.6364,  ...,  0.2674, -1.0874, -1.0255],
         [ 0.8648, -0.2718, -0.2358,  ...,  0.0800,  0.3331, -0.3003],
         ...,
         [ 0.7806, -0.1691, -0.1629,  ..., -0.3242,  0.3747, -0.3008],
         [-0.3772, -0.0128, -0.0039,  ...,  0.7667, -0.2033,  0.0784],
         [ 0.1820, -0.5237, -0.2857,  ...,  0.8096, -0.4868, -0.3264]]],
       grad_fn=<AddBackward0>)

In [7]:
model(x)

tensor([[[ 0.1300, -0.4375, -0.2455,  ...,  0.8411, -0.4022, -0.2514],
         [ 0.8082, -1.2566, -0.6365,  ...,  0.2675, -1.0875, -1.0256],
         [ 0.8649, -0.2718, -0.2358,  ...,  0.0801,  0.3331, -0.3003],
         ...,
         [ 0.7807, -0.1691, -0.1629,  ..., -0.3243,  0.3747, -0.3008],
         [-0.3772, -0.0128, -0.0039,  ...,  0.7668, -0.2034,  0.0785],
         [ 0.1820, -0.5238, -0.2857,  ...,  0.8097, -0.4869, -0.3265]]],
       grad_fn=<ViewBackward0>)

In [8]:
model(x).shape

torch.Size([1, 100, 64])

In [9]:
criterion = torch.nn.MSELoss()

In [10]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.0003)

In [11]:
for epoch in range(10):
    output = model(x)
    loss = criterion(output, target)
    print('Epoch: ', epoch, 'Loss: ', loss.item())
    optimizer.zero_grad()  # w.grad, b.grad - reset to zero
    loss.backward()  # update w.grad, b.grad
    optimizer.step()

Epoch:  0 Loss:  1.4546034336090088
Epoch:  1 Loss:  1.4545936584472656
Epoch:  2 Loss:  1.454584002494812
Epoch:  3 Loss:  1.454574465751648
Epoch:  4 Loss:  1.4545645713806152
Epoch:  5 Loss:  1.4545550346374512
Epoch:  6 Loss:  1.454545259475708
Epoch:  7 Loss:  1.4545354843139648
Epoch:  8 Loss:  1.4545259475708008
Epoch:  9 Loss:  1.4545161724090576


In [12]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3481,  0.1526,  0.4837],
         [ 0.1686, -0.3915, -0.3878],
         [ 0.0504, -0.1552, -0.2153],
         [-0.5001, -0.2540, -0.3867],
         [-0.5136, -0.2870, -0.1281],
         [-0.4881, -0.2401,  0.5566],
         [-0.5134, -0.2754, -0.0076],
         [-0.1999, -0.3898,  0.5440],
         [ 0.4712, -0.3701, -0.5441],
         [ 0.4660, -0.2254, -0.3535],
         [ 0.0115,  0.1406,  0.3809],
         [-0.0213, -0.4408,  0.3618],
         [-0.1610, -0.2271, -0.4691],
         [-0.2551,  0.4789,  0.0892],
         [ 0.4885,  0.5189,  0.3329],
         [ 0.4318, -0.2709,  0.0341],
         [-0.4906,  0.1566,  0.4521],
         [ 0.3492, -0.0289, -0.1082],
         [ 0.1997,  0.1924, -0.3111],
         [-0.1856, -0.3339, -0.5330],
         [-0.4725,  0.3371, -0.1913],
         [-0.1146,  0.4475, -0.1892],
         [ 0.0408,  0.4336, -0.1681],
         [ 0.3659, -0.5187, -0.4996],
         [-0.5328, -0.2555, -0.2976],
         [ 0.5625,  0.1655,