In [3]:
import torch

In [4]:
x = torch.randn([1, 100, 3])
target = torch.randn([1, 100, 64])

In [5]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(3, 64)  # w*x+b, w - weight, b - bias

    def forward(self, x):  # __call__ -> forward()
        x = self.fc1(x)
        return x

In [6]:
model = Net()

In [7]:
model(x)

tensor([[[-0.4967,  0.0583, -0.1832,  ...,  0.6181,  0.4412, -0.3128],
         [ 0.7607,  1.4842, -0.6518,  ..., -0.2622,  0.2063,  1.3844],
         [ 0.7761, -0.3824, -0.1793,  ...,  0.3719,  0.6031,  0.7978],
         ...,
         [-0.0150, -0.0160, -0.3013,  ...,  0.4636,  0.4203,  0.1808],
         [-0.0439, -0.6877,  0.6054,  ...,  0.9294,  1.0390, -0.3969],
         [-0.0914, -0.9447,  0.3425,  ...,  0.9295,  0.8747, -0.3758]]],
       grad_fn=<ViewBackward0>)

In [8]:
model(x).shape

torch.Size([1, 100, 64])

In [9]:
criterion = torch.nn.MSELoss()

In [10]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.0003)

In [14]:
for epoch in range(1):
    output = model(x)
    loss = criterion(output, target)
    print('Epoch: ', epoch, 'Loss: ', loss.item())
    optimizer.zero_grad()  # w.grad, b.grad - reset to zero
    loss.backward()  # update w.grad, b.grad

Epoch:  0 Loss:  1.4975323677062988


In [15]:
list(model.parameters())[0].grad

tensor([[-5.6454e-04, -1.4393e-02,  4.7372e-05],
        [ 1.2397e-02, -1.3343e-02,  1.4096e-02],
        [-1.4512e-02, -7.0489e-03,  1.5656e-02],
        [ 6.8453e-03, -1.0503e-02, -1.1035e-02],
        [ 4.0951e-03, -5.0044e-03,  1.0639e-02],
        [ 1.8642e-02, -2.6714e-03,  1.5356e-02],
        [-1.6502e-02, -1.0274e-02,  1.1011e-02],
        [-4.5279e-03,  1.2325e-02,  3.3965e-03],
        [-3.5179e-03, -5.9001e-04,  2.0788e-02],
        [ 9.8727e-03,  5.6056e-03,  4.1611e-04],
        [-1.8850e-02,  5.5423e-04,  3.1448e-02],
        [-8.5560e-03,  1.6799e-02, -3.7231e-03],
        [ 2.4863e-03, -6.6277e-03, -2.3290e-02],
        [-7.3940e-03, -8.7204e-03, -1.5395e-02],
        [-3.7774e-03,  9.7503e-03,  2.2968e-02],
        [-1.9189e-04,  1.4015e-02,  1.3925e-02],
        [-5.3261e-03,  1.0752e-02,  2.1865e-02],
        [-1.7907e-02,  1.8933e-02,  1.5690e-02],
        [ 2.8044e-04, -1.4528e-02,  7.8322e-03],
        [-4.0076e-03,  9.4995e-03, -3.1002e-03],
        [ 8.2052e-03

In [17]:
optimizer.zero_grad()

In [18]:
list(model.parameters())[0].grad

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0